- name: stop syslog-ng
  shell: sudo /sbin/service syslog-ng stop
  become: true
  become_user: syslog-ng

- name: start syslog-ng
  shell: sudo /sbin/service syslog-ng start
  become: true
  become_user: syslog-ng

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=300 delay=30
  ignore_errors: yes