- name: stop syslog-ng
  shell: /sbin/service syslog-ng stop
  become: true
  become_user: syslog-ng

- name: start syslog-ng
  shell: /sbin/service syslog-ng start
  become: true
  become_user: syslog-ng