########################################################################################################################## 
# ansible-playbook create_symlink_to_git_master_repo.yml  -e "SOURCE_FOLDER=splunk_7_0_overview" --ask-vault #############
# ansible-playbook create_symlink_to_git_master_repo.yml  -e "SOURCE_FOLDER=splunk_7_0_overview" -t all-cm --ask-vault ###
##########################################################################################################################

- hosts: stl-sd
  gather_facts: no
  become: true
  become_user: splunk
  tasks:
  - name: Run git pull on Search Deployer
    shell: 'cd /opt/splunk/Splunk-Configs;git pull'
    register: pull_status
    until: pull_status|succeeded
  - debug: var=pull_status.stdout

  - name: Create Symbolic link for SearchDeployer App/Add-on
    file:
     src: "/opt/splunk/Splunk-Configs/search-deployer/{{ SOURCE_FOLDER }}"
     dest: "/opt/splunk/etc/shcluster/apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - stl-sd

- hosts: all-cm
  gather_facts: no
  become: true
  become_user: splunk
  tasks:
  - name: Run git pull on all Cluster Master servers.
    shell: 'cd /opt/splunk/Splunk-Configs;git pull'
    register: pull_status
    until: pull_status|succeeded
  - debug: var=pull_status.stdout

  - name: Create Symbolic link for Cluster Master App/Add-on
    file:
     src: "/opt/splunk/Splunk-Configs/indexer-cluster/master-apps/{{ SOURCE_FOLDER }}"
     dest: "/opt/splunk/etc/master-apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - all-cm

- hosts: stl-ds
  gather_facts: no
  become: true
  become_user: splunk
  tasks:
  - name: Run git pull on Deployment server.
    shell: 'cd /opt/splunk/Splunk-Configs;git pull'
    register: pull_status
    until: pull_status|succeeded
  - debug: var=pull_status.stdout

  - name: Create Symbolic link for Deployment Server App/Add-on
    file:
     src: "/opt/splunk/Splunk-Configs/deployment-server/deployment-apps/{{ SOURCE_FOLDER }}"
     dest: "/splunkds/deployment-apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - stl-ds

- hosts: all-hf
  gather_facts: no
  become: true
  become_user: splunk
  tasks:
  - name: Run git pull on heavy-forwarder.
    shell: 'cd /opt/splunk/Splunk-Configs;git pull'
    register: pull_status
    until: pull_status|succeeded
  - debug: var=pull_status.stdout

  - name: Create Symbolic link for Deployment Server App/Add-on
    file:
     src: "/opt/splunk/Splunk-Configs/heavy-forwarder/{{ SOURCE_FOLDER }}"
     dest: "/opt/splunk/etc/apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - all-hf
