########################################################################################################################## 
# ansible-playbook create_symlink_to_git_master_repo.yml  -e "SOURCE_FOLDER=splunk_7_0_overview" --ask-vault #############
# ansible-playbook create_symlink_to_git_master_repo.yml  -e "SOURCE_FOLDER=splunk_7_0_overview" -t all-cm --ask-vault ###
##########################################################################################################################

- hosts: stl-sd
  gather_facts: no
  name: Create Symbolic link for SearchDeployer App/Add-on
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:     
  - file:
     src: "/opt/splunk/Splunk-Configs/search-deployer/{{ SOURCE_FOLDER }}"
     dest: "/opt/splunk/etc/shcluster/apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - stl-sd

- hosts: all-cm
  gather_facts: no
  name: Create Symbolic link for Cluster Master App/Add-on
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - file:
     src: "/opt/splunk/Splunk-Configs/indexer-cluster/master-apps/{{ SOURCE_FOLDER }}"
     dest: "/opt/splunk/etc/master-apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - all-cm

- hosts: stl-ds
  gather_facts: no
  name: Create Symbolic link for Deployment Server App/Add-on
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:     
  - file:
     src: "/opt/splunk/Splunk-Configs/deployment-server/deployment-apps/{{ SOURCE_FOLDER }}"
     dest: "/splunkds/deployment-apps/{{ SOURCE_FOLDER }}"
     state: link
  tags:
    - stl-ds
