- hosts: all-cm
  serial: 100
  name: enable clustermaster maintenance mode in all regions
  become: yes
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - block:
        - include: tasks/disable_cm_maintenance_mode.yml
