- hosts: skcm_*
  roles:
    - role: splunk_cluster_master_node

# Enable maintenance mode
- include: enable_maintenance_mode.yml

# copy and remove distsearch stanza in /etc/system/local/distsearch.conf on all searchheads
- include: copy_remove_distributedsearch.yml

- hosts: skid_usstl
  roles:
    - role: splunk_cluster_peer_usstl

- hosts: skid_gblo
  roles:
    - role: splunk_cluster_peer_gblo

- hosts: skid_cnhk
  roles:
    - role: splunk_cluster_peer_cnhk

# disable maintainence mode on cluster masters
- include: disable_maintenance_mode.yml

- hosts: sksh
  roles:
    - role: splunk_integrate_sh_cluster_with_idx_cluster
