- hosts: skcm_*
  serial: 100
  gather_facts: no
  roles:
    - role: splunk_cluster_master_node

# Enable maintenance mode
- include: enable_maintenance_mode.yml

# copy and remove distsearch stanza in /etc/system/local/distsearch.conf on all searchheads
- include: copy_remove_distributedsearch.yml

- hosts: skid_usstl
  serial: 1
  gather_facts: no
  roles:
    - role: splunk_cluster_peer_usstl

- hosts: skid_gblo
  serial: 50
  strategy: debug
  gather_facts: no
  roles:
    - role: splunk_cluster_peer_gblo

- hosts: skid_cnhk
  serial: 50
  gather_facts: no
  roles:
    - role: splunk_cluster_peer_cnhk

# disable maintainence mode on cluster masters
- include: disable_maintenance_mode.yml

- hosts: sksh
  serial: 100
  gather_facts: no
  roles:
    - role: splunk_integrate_sh_cluster_with_idx_cluster
