- hosts:  skcm
  roles:
    - role: splunk_cluster_master_node

- hosts: skid_usstl
  roles:
    - role: splunk_cluster_peer_usstl

- hosts: skid_gblo
  roles:
    - role: splunk_cluster_peer_gblo

- hosts: skid_cnhk
  roles:
    - role: splunk_cluster_peer_cnhk

- hosts: sksh
  roles:
    - role: splunk_integrate_sh_cluster_with_idx_cluster
