---

- hosts: skdr
  serial: 100%
  name: Prepare for upgrade
  become: true
  become_user: splunk
  tasks:
  - block:
        - include: tasks/apply_version_6_2_deployer.yml

- hosts: sksh*
  serial: 100%
  name: Prepare for upgrade
  become: true
  become_user: splunk
  tasks:
  - block:
        - include: tasks/apply_version_6_2_searchheads.yml


- hosts: skdp
  serial: 100%
  name: Prepare for upgrade
  become: true
  become_user: splunk
  tasks:
  - block:
        - include: tasks/apply_version_6_2_deploymentserver.yml
