---
# Restart the splunk process
# #
# # Usage: ansible-playbook -i <inventory> -l <pattern>
# #
# # Examples:
# #  Restart current heavy forwarder servers:
# #     ansible-playbook -i <inventory> -l "all-hf*" restart_splunk.yml
# #
# #  Restart one heavy forwarder:
# #     ansible-playbook -i <inventory> -l "usstlecpsecap41" restart_splunk.yml
# #
# #
# Run git pull on all servers.
- hosts: all-hf
  serial: 100
  gather_facts: no
  become: true
  become_user: splunk
  tasks:
    - include: tasks/run_git_pull.yml

- hosts: all-hf
  serial: 25%
  gather_facts: no
  become: true
  become_user: splunk
  name: Restart the Splunk service
  tasks:
  - include: tasks/restart_splunk_service.yml
