---
# Restart the splunk process
# #
# # Usage: ansible-playbook -i <inventory> -l <pattern>
# #
# # Examples:
# #  Restart current heavy forwarder servers:
# #     ansible-playbook -i <inventory> -l "all-hf*" restart_splunk.yml
# #
# #  Restart one heavy forwarder:
# #     ansible-playbook -i <inventory> -l "usstlecpsecap41" restart_splunk.yml
# #
# #
- hosts: all-hf
  serial: 25%
  vars_prompt:
  - name: RESTART_CONFIRMED
    prompt: "This will restart splunk. Did you specify a subset (-l) (True/False)"
    default: no
    private: no
  - name: Restart the Splunk service
  tasks:
  - include: tasks/restart_splunk_service.yml
