- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host captain
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: sksh

- hosts: sksh
  serial: 1
  become: true
  become_user: splunk
  tasks:
  - name: SearchHead rolling-restart
    action: /opt/splunk/bin/splunk rolling-restart shcluster-members
