# before reload, run git pull on all server 
- include: git_pull.yml

# reload deployment server
- hosts: usstlecpsplds01
  serial: 100
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - role: splunk_deployment_server