# Run git pull on Cluster Masters.
- hosts: all-cm
  serial: 100
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: pull from git
    shell: 'cd /opt/splunk/Splunk-Configs;git pull'
    register: pull_status
    until: pull_status|succeeded
  - debug: var=pull_status.stdout
    tags:
       - git_pull

- hosts: all-cm
  serial: 100
  gather_facts: no
  name: apply cluster bundle in all regions
  become: yes
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - role: splunk_cluster_master_node
