# Run git pull on ds02 server.
- hosts: stl-ds
  name: run git pull on ds02 and reload deployment server.
  serial: 100
  gather_facts: no
  become: true
  become_user: splunk
  roles:
    - git
    - splunk_deployment_server
