# Run git pull on Search Deployer.
- hosts: stl-sd
  name: run git pull and apply SH cluster bundle
  serial: 100
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - git
    - splunk_cluster_deployer
