# Run git pull on Search Deployer.
- hosts: all-cm
  name: run git pull and apply idx cluster bundle
  serial: 100
  gather_facts: no
  become: true
  become_user: splunk
  roles:
    - git
    - splunk_cluster_master_node
