# before reload, run git pull on all server 
- hosts: stl-sd
  serial: 50
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: pull from git
    shell: 'cd /opt/splunk/Splunk-Configs;git pull'
    register: pull_status
    until: pull_status|succeeded
  - debug: var=pull_status.stdout
    tags:
       - git_pull

# Splunk reload deploy-server
- hosts: stl-ds
  serial: 100
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - { role: 'splunk_deployment_server' }
