# before apply shcluster bundle, run git pull on all server 
- include: git_pull.yml

- hosts: usstlecpsplds02
  serial: 100
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - role: splunk_cluster_deployer

- hosts: localhost
  any_errors_fatal: yes
  vars_prompt:
    name: "confirmation"
    prompt: "Are you sure you want to restart the Splunk Service? Answer with 'YES'"
    default: "NO"
    private: no

  tasks:
    - name: Check Confirmation
      fail: msg="Playbook run confirmation failed"
      when: confirmation != "YES"

- include: splunk_search_head_rolling_restart.yml