# before apply shcluster bundle, run git pull on all server 
- include: git_pull.yml

- hosts: all-cm
  serial: 100
  gather_facts: no
  name: apply cluster bundle in all regions
  become: yes
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - role: splunk_cluster_master_node
