- hosts: usstlecpsplds02
  serial: 100
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: apply shcluster bundle from deployer
    shell: /opt/splunk/bin/splunk apply shcluster-bundle --answer-yes -target https://{{ item }}.emrsn.org:8089 -auth "{{ SPLUNK_ADMIN }}:{{ splunk_new_password }}"
  with_items:
  - usstlecpsplsh01
  - usstlecpsplsh02
  - usstlecpsplsh03
  - usstlecpsplsh04
  - usstlecpsplsh05

---

# INFO: Verify captain via a splunk search
#
- hosts: usmtnecdsplsh01
  serial: 1
  name: Verify search heads
  vars_prompt:
  - name: SPLUNK_USER_NAME
    promt: "Splunk User ID"
    private: no
  - name: SPLUNK_USER_PWD
    promt: "Splunk Password"
    private: yes
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: Get_Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain' -auth "{{ SPLUNK_USER_NAME }}:{{ SPLUNK_USER_PWD }}"
    register: search_output
  - debug: var=search_output.stdout_lines

# Apply shcluster bundle
- hosts: usmtnecdsplsd01
  serial: 100
  become: true
  become_user: "{{ SPLUNK_USER }}"
  vars_prompt:
  - name: SPLUNK_USER_NAME
    promt: "Splunk User ID"
    private: no
  - name: SPLUNK_USER_PWD
    promt: "Splunk Password"
    private: yes
  - name: Captain
    promt: "Copy the Captain"
    private: no
  tasks:
  - name: apply shcluster bundle from deployer
    shell: /opt/splunk/bin/splunk apply shcluster-bundle --answer-yes -target https://"{{Captain}}".emrsn.org:8089 -auth "{{ SPLUNK_USER_NAME }}:{{ SPLUNK_USER_PWD }}"

- hosts: localhost
  serial: 1
  vars_prompt:
  - name: target_host
    prompt: please select the target captain
    private: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: sksh_captain


# INFO: Apply the SearchHead rolling-restart

- hosts: sksh_captain
  serial: 1
  vars_prompt:
  - name: SPLUNK_USER_NAME
    promt: "Splunk User ID"
    private: no
  - name: SPLUNK_USER_PWD
    promt: "Splunk Password"
    private: yes
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: SearchHead rolling restart
    shell: /opt/splunk/bin/splunk rolling-restart shcluster-members -auth "{{ SPLUNK_USER_NAME }}:{{ SPLUNK_USER_PWD }}"
