# before reload, run git pull on all server 
- include: git_pull.yml

# Splunk reload deploy-server
- hosts: stl-ds
  serial: 100
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  roles:
    - { role: 'splunk_deployment_server' }
