# Run git pull on all servers
- include: git_pull.yml

# Display syslog-ng .conf file names
- hosts: stl-ds
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
    - include: tasks/get_syslog_ng_conf_names.yml

- hosts: all-hf
  gather_facts: no
  become: true
  become_user: syslog-ng
  vars_prompt:
    - name: syslog-ng
      prompt: Please enter the syslog-ng file name
      private: false
  pre_tasks:
    - name: "set_vars"
      set_fact: syslog-ng={{ syslog-ng }}
  tasks: 
  - name: copy syslog-ng file to buckets.d
    copy:
      src: /opt/splunk/Splunk-Configs/syslog-ng/buckets.d/"{{ syslog-ng }}""
      dest: /etc/syslog-ng/buckets.d/
      owner: syslog-ng
      group: syslog-ng
      remote_src: yes
      mode: 0644

- hosts: all-hf
  serial: 100
  gather_facts: no
  become: true
  become_user: syslog-ng
  roles:
    - { role: 'splunk_syslog-ng' }