# Run git pull on all servers
#- include: git_pull.yml

# Display syslog-ng .conf file names
- hosts: stl-ds
  gather_facts: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
    - include: tasks/get_syslog_ng_conf_names.yml

- hosts: all-hf
  gather_facts: no
  become: true
  become_user: "{{ syslog_ng_user }}"
  vars_prompt:
    - name: syslog
      prompt: Please enter the syslog-ng file name
      private: false
  pre_tasks:
    - name: "set_vars"
      set_fact: syslog={{ syslog }}
  tasks: 
  - name: copy syslog-ng file to buckets.d
    copy:
      src: /opt/splunk/Splunk-Configs/syslog-ng/buckets.d/{{syslog}}
      dest: /etc/syslog-ng/buckets.d/
      owner: syslog-ng
      group: syslog-ng
      remote_src: yes
      mode: 0644

- hosts: hkg-hf
  gather_facts: no
  become: true
  tasks:
    - name: Stop the syslog-ng, if running
      shell: service syslog-ng stop
  
    - name: Start the syslog-ng, if stoppped
      shell: service syslog-ng start
  
    - name: Status of the syslog-ng
      shell: service syslog-ng status

#- hosts: all-hf
#  serial: 1
#  gather_facts: no
#  become: true
#  become_user: syslog-ng
#  roles:
#    - { role: 'splunk_syslog-ng' }