# Run git pull on Heavy Forwarders
- hosts: all-hf
  name: run git pull on Heavy Forwarders
  serial: 100%
  gather_facts: no
  become: true
  become_user: splunk
  roles:
    - git

# Display syslog-ng .conf file names
- hosts: usstlecpsplhf01
  gather_facts: no
  become: true
  become_user: splunk
  tasks:
    - include: tasks/get_syslog_ng_conf_names.yml

- hosts: all-hf
  gather_facts: no
  become: true
  become_user: "{{ syslog_ng_user }}"
  vars_prompt:
    - name: syslog
      prompt: Please enter the syslog-ng file name
      private: false
  pre_tasks:
    - name: "set_vars"
      set_fact: syslog={{ syslog }}
  tasks: 
  - name: copy syslog-ng file to buckets.d
    copy:
      src: /opt/splunk/Splunk-Configs/syslog-ng/buckets.d/{{syslog}}
      dest: /etc/syslog-ng/buckets.d/
      owner: syslog-ng
      group: syslog-ng
      remote_src: yes
      mode: 0644
  tags:
     - copy

- hosts: all-hf
  serial: 1%
  gather_facts: no
  become: false
  tasks:
    - name: Stop the syslog-ng, if running
      shell: sudo /sbin/service syslog-ng stop
      ignore_errors: yes
      register: syslog_status
    - debug: var=syslog_status.stdout_lines
  
    - name: Start the syslog-ng, if stoppped
      shell: sudo /sbin/service syslog-ng start
      ignore_errors: yes
      register: syslog_status
    - debug: var=syslog_status.stdout_lines
  
    - name: Status of the syslog-ng
      shell: sudo /sbin/service syslog-ng status
      ignore_errors: yes
      register: syslog_status
    - debug: var=syslog_status.stdout_lines
  tags:
     - restart
     