---

# INFO: Verify captain via a splunk search
#
- hosts: usmtnecdsplsh01
  serial: 1
  name: Verify search heads
  vars_prompt:
  - name: MODE
#    prompt: "Display Captain"
#    private: no
    default: Captain
  become: true
  become_user: splunk
  tasks:
  - name: Get_Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain' -earliest_time -30m -preview false -output table -app search
    register: search_output
    when: MODE == "Captain"
  - debug: var=search_output.stdout_lines
    when: MODE == "Captain"

- hosts: localhost
  serial: 1
  vars_prompt:
  - name: target_host
    prompt: please enter the target host captain
    private: no
  become: true
  become_user: splunk
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: sksh_captain

- hosts: sksh_captain
  serial: 1
  vars_prompt:
  - name: SPLUNK_USER
    promt: "Splunk User ID"
    private: no
  - name: SPLUNK_PWD
    promt: "Splunk Password"
    private: yes
  become: true
  become_user: splunk
  tasks:
  - name: SearchHead rolling restart
    shell: /opt/splunk/bin/splunk rolling-restart shcluster-members -auth "{{ SPLUNK_USER }}:{{ SPLUNK_PWD}}""
