---

# INFO: Verify captain via a splunk search
#
- hosts: usstlecpsecap43
  serial: 1
  name: Verify search heads
  - name: MODE
    prompt: "Display Captain"
    private: no
    default: Captain
  become: true
  become_user: splunk
  tasks:
  - name: Get Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain' -earliest_time -30m -preview false -output table -app search"
    register: search_output
    when: MODE == "Captain"
  - debug: var=search_output.stdout_lines
    when: MODE == "Captain"
