---

# INFO: Verify captain via a splunk search
#
- hosts: usstlecpsecap43
  serial: 1
  name: Verify search heads
  become: true
  become_user: splunk
  tasks:
  - name: Get Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain'
    register: search_output
