---

# INFO: Verify captain via a splunk search
#
- hosts: localhost
  serial: 1
  name: Verify search heads
  vars_prompt:
  - name: SPLUNK_USER
    promt: "Splunk User ID"
    private: no
  - name: SPLUNK_PWD
    promt: "Splunk Password"
    private: yes
  - name: MODE
    prompt: "Display Captain"
    private: no
    default: Captain
  become: true
  become_user: splunk
  tasks:
  - name: Get_Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain' -earliest_time -30m -preview false -output table -app search -auth "{{ SPLUNK_USER }}:{{ SPLUNK_PWD}}"
    register: search_output
    when: MODE == "Captain"
  - debug: var=search_output.stdout_lines
    when: MODE == "Captain"

  tasks:
    - add_host:
        name: "{{ Get_Captain }}"
        groups: sksh_captain

- hosts: sksh_captain
  serial: 1
  become: true
  become_user: splunk
  tasks:
  - name: SearchHead rolling restart
    action: shell /opt/splunk/bin/splunk rolling-restart shcluster-members
