---

# INFO: Verify captain via a splunk search
#
- hosts: usmtnecdsplsh01
  serial: 1
  name: Verify search heads
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: Get_Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain -auth "{{ SPLUNK_ADMIN }}:{{ splunk_new_password }}"'
    register: search_output
  - debug: var=search_output.stdout_lines

- hosts: localhost
  serial: 1
  vars_prompt:
  - name: target_host
    prompt: please select the target captain
    private: no
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: sksh_captain

# INFO: Apply the SearchHead rolling-restart

- hosts: sksh_captain
  serial: 1
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: SearchHead rolling restart
    shell: /opt/splunk/bin/splunk rolling-restart shcluster-members -auth "{{ SPLUNK_ADMIN }}:{{ splunk_new_password }}"
