- name: copy indexes.conf
  copy:
    src: opt/splunk/etc/system/local/indexes.conf
    dest: /opt/splunk/etc/system/local/indexes.conf
    owner: splunk
    group: splunk
    mode: 0654
  become: true
  become_user: "{{ SPLUNK_USER }}"
