- name: copy deployer apps
  copy:
    src=/export/home/mmuralikri/shcluster/{{ item }}
    dest=/opt/splunk/etc/shcluster/apps/
  with_items:
  - emr-cirt-global-SH-microservice
  become: true
  become_user: "{{ SPLUNK_USER }}"
