  - name: Create Symbolic link for HeavyForwarder App/Add-on
    file:
     src: "/opt/splunk/Splunk-Configs/search-deployer/{{ item.path }}"
     dest: "/opt/splunk/etc/shcluster/apps/{{ item.dest }}"
     state: link
    with_items:
    - {path: 'emr_all_hf_base', dest: 'emr_all_hf_base'}
    - {path: 'global_hfs_props', dest: 'global_hfs_props'}
    - {path: 'global_indexers_build', dest: 'global_indexers_build'}
    - {path: 'global_syslog_inputs', dest: 'global_syslog_inputs'}
    - {path: 'global_unix_inputs', dest: 'global_unix_inputs'}
    - {path: 'isamonitor', dest: 'isamonitor'}
    - {path: 'splunk_app_infrastructure', dest: 'splunk_app_infrastructure'}
    - {path: 'Splunk_TA_bro_json', dest: 'Splunk_TA_bro_json'}
    - {path: 'Splunk_TA_bro_props', dest: 'Splunk_TA_bro_props'}
    - {path: 'Splunk_TA_cisco-asa', dest: 'Splunk_TA_cisco-asa'}
    - {path: 'Splunk_TA_cisco-esa', dest: 'Splunk_TA_cisco-esa'}
    - {path: 'Splunk_TA_cisco-ise', dest: 'Splunk_TA_cisco-ise'}
    - {path: 'Splunk_TA_cloudsoc', dest: 'Splunk_TA_cloudsoc'}
    - {path: 'Splunk_TA_idrac', dest: 'Splunk_TA_idrac'}
    - {path: 'Splunk_TA_infoblox', dest: 'Splunk_TA_infoblox'}
    - {path: 'Splunk_TA_Infrastructure', dest: 'Splunk_TA_Infrastructure'}
    - {path: 'Splunk_TA_microsoft-sqlserver', dest: 'Splunk_TA_microsoft-sqlserver'}
    - {path: 'Splunk_TA_mvp', dest: 'Splunk_TA_mvp'}
    - {path: 'Splunk_TA_netinfo', dest: 'Splunk_TA_netinfo'}
    - {path: 'Splunk_TA_oracle', dest: 'Splunk_TA_oracle'}
    - {path: 'Splunk_TA_paloalto', dest: 'Splunk_TA_paloalto'}
    - {path: 'Splunk_TA_salesforce', dest: 'Splunk_TA_salesforce'}
    - {path: 'Splunk_TA_san', dest: 'Splunk_TA_san'}
    - {path: 'Splunk_TA_symantec-dlp', dest: 'Splunk_TA_symantec-dlp'}
    - {path: 'Splunk_TA_Titus', dest: 'Splunk_TA_Titus'}
    - {path: 'Splunk_TA_vcenter', dest: 'Splunk_TA_vcenter'}
    - {path: 'Splunk_TA_Zscaler', dest: 'Splunk_TA_Zscaler'}
    - {path: 'Splunk_UF_agent', dest: 'Splunk_UF_agent'}
    - {path: 'SSL-versions', dest: 'SSL-versions'}
    - {path: 'TA-cisco-acs', dest: 'TA-cisco-acs'}
    - {path: 'TA-Damballa-Failsafe-520-v101', dest: 'TA-Damballa-Failsafe-520-v101'}
    - {path: 'TA-ms-loganalytics', dest: 'TA-ms-loganalytics'}
    - {path: 'TA-MS_O365_Reporting', dest: 'TA-MS_O365_Reporting'}
    - {path: 'TA-ObserveIT', dest: 'TA-ObserveIT'}
    - {path: 'TA_pps', dest: 'TA_pps'}
    - {path: 'TA-Proofpoint-TAP', dest: 'TA-Proofpoint-TAP'}
    - {path: 'TA-sailpoint-identitynow-auditevent-add-on', dest: 'TA-sailpoint-identitynow-auditevent-add-on'}
    - {path: 'TA_sudo', dest: 'TA_sudo'}
    - {path: 'VMwareNSXAppforSplunk', dest: 'VMwareNSXAppforSplunk'}
