- name: install cluster_master_app
  copy:
    src: cluster_master_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=30
  ignore_errors: yes

- name: configure pass4SymmKey
  splunk_config_stanza:
   auth_user: admin
   auth_password: "{{ splunk_new_password }}"
   app: cluster_master_app
   file: server
   stanza: shclustering
   values:
     pass4SymmKey: "{{ sh_cluster_secret }}"
   splunklib: "{{ splunklib_1_6_6_location }}/splunklib-1.6.6"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=30
  ignore_errors: yes

