# INFO: Verify captain via a splunk search
- hosts: usmtnecdsplsh01
  serial: 1
  name: Verify search heads
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: Get_Captain
    action: shell /opt/splunk/bin/splunk search '| rest splunk_server=local /services/shcluster/captain/info | rename label as Captain | fields Captain' -auth admin:"{{ splunk_new_password }}"
    register: search_output
  - debug: var=search_output.stdout_lines

# Apply shcluster bundle
- hosts: usmtnecdsplsd01
  serial: 100
  become: true
  become_user: "{{ SPLUNK_USER }}"
  tasks:
  - name: apply shcluster bundle from deployer
    shell: /opt/splunk/bin/splunk apply shcluster-bundle --answer-yes -target https://"{{Captain}}".emrsn.org:8089 -auth admin:"{{ splunk_new_password }}"
