- name: install cluster_master_app
  copy:
    src: cluster_master_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=30
  ignore_errors: yes

- name: configure pass4SymmKey for sh cluster
  splunk_config_stanza:
   auth_user: admin
   auth_password: "{{ splunk_new_password }}"
   app: cluster_master_app
   file: server
   stanza: shclustering
   values:
     conf_deploy_fetch_url: https://usmtnecdsplsd01:8089
     disabled: 0
     mgmt_uri: https://{{ ansible_hostname }}:8089
     pass4SymmKey: "{{ sh_cluster_secret }}"
     replication_factor: 2
     shcluster_label: shcluster1
   splunklib: "{{ splunklib_1_6_6_location }}/splunklib-1.6.6"

- name: configure indexer master-uri on searcheads
  splunk_config_stanza:
   auth_user: admin
   auth_password: "{{ splunk_new_password }}"
   app: cluster_master_app
   file: server
   stanza: clustering
   values:
     mode: searchhead
     master_uri: https://usmtnecdsplhf01:8089
     pass4SymmKey: "{{ cluster_secret }}"
   splunklib: "{{ splunklib_1_6_6_location }}/splunklib-1.6.6"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=30
  ignore_errors: yes
