---

- name: Ensure Splunk is Started
  command: /opt/splunk/bin/splunk start --answer-yes --no-prompt --accept-license
  ignore_errors: yes

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=900 delay=30
  ignore_errors: yes