- name: unpack apps.tgz
  unarchive:
    src: "{{ SPLUNK_BINARY_APP }}"
    dest: "/opt/splunk/etc/master-apps/.."
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: install cluster_master_app
  copy:
    src: cluster_master_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=300 delay=30
  ignore_errors: yes
