- name: install cluster_master_app
  copy:
    src: cluster_master_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: configure pass4SymmKey
  validate_certs: false
  splunk_config_stanza:
   auth_user: admin
   auth_password: "{{ splunk_new_password }}"
   app: cluster_master_app
   file: server
   stanza: clustering
   values:
     mode: master
     pass4SymmKey: "{{ cluster_secret }}"
   splunklib: "{{ splunklib_1_6_2_location }}/splunklib-1.6.2"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=300 delay=30
  ignore_errors: yes
