---

- name: unpack splunk.tar.gz

  unarchive:
    src: "{{ SPLUNK_BINARY }}"
    #dest is $SPLUNK_HOME/.., as the tarball contains splunk/ directory
    dest: "{{ SPLUNK_HOME }}/.."
    creates: "{{ SPLUNK_HOME }}/splunk-7.3.2-c60db69f8e32-Linux-x86_64-mainfest"
    